### ISSUE TITLE
add support for assertion on primitive types

### ISSUE THREAD

**Issue by monperrus** [castor-software/pankti#17]
if the method returns a primitive type, we hould generate

    Assert.assertEquals(<value>, receivingObject.isClosing(paramObject1));    
    // eg
    Assert.assertEquals(1, receivingObject.isClosing(paramObject1));

if the parameters are primitive, we put directly in the called method as argument 

    Assert.assertEquals(1, receivingObject.isClosing(<value>));
    Assert.assertEquals(1, receivingObject.isClosing(1));

**Comment by monperrus** [comment]
There is useless code related to primitive types.

```
String returnedXML = 
        "<boolean>false</boolean>";
boolean expectedObject = (Boolean) xStream.fromXML(returnedXML);
Assert.assertEquals(false, receivingObject.useRoomAsSharedDocName());
```

We can remove `returnedXML` and `expectedObject`:

**Comment by Deee92** [comment]
How about not removing `returnedXML` to make the "object profile" (receiving, parameters, returned objects) available in the generated test case?

**Comment by monperrus** [comment]
How would this be useful for the users of Pankti?

**Comment by Deee92** [comment]
It would be consistent with test cases with non-primitive types. Do you think it might help to see the serialized form of the all three objects involved?

**Comment by monperrus** [comment]
> It would be consistent with test cases with non-primitive types. 

It's not an issue.

> Do you think it might help to see the serialized form of the all three objects involved?

Right now, I don't see how this would be useful for the developer. IMHO 
it's actually confusing.

**Comment by Deee92** [comment]
I see, thanks! Working on it next.

**Comment by Deee92** [comment]
Hi @monperrus, some updates about this issue:

- If the returned object is a primitive or is `null`, it is included in the assertion directly
  - XML strings and deserialization statements for these objects are not added to the generated test method
- If *all* the parameters to a method are primitive, they appear in the assertion directly
  - XML strings and deserialization statements for these objects are not added to the generated test method
  - Since we currently parse these values from XML strings in pankti-generate, it's more complicated to differentiate between an individual int parameter and an int value inside an arbitrarily nested object parameter, hence the *all*-primitive-parameters condition 

Examples: 
`Assert.assertEquals(null, receivingObject.getName(1, 0, 4, 0))`
`Assert.assertEquals(expectedObject, receivingObject.getName(1, 3, 1, 1033));`
`Assert.assertEquals(1479, receivingObject.getAdvanceWidth(37));`

And not this:
`Assert.assertEquals(99, receivingObject.someMethod(99, paramObject2));`

WDYT?

**Comment by monperrus** [comment]
that's great
